<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace SellingPartnerApi\Seller\ShippingV2\Dto;

use SellingPartnerApi\Dto;

final class AmazonOrderDetails extends Dto
{
    /**
     * @param  string  $orderId  The Amazon order ID associated with the Amazon order fulfilled by this shipment.
     * @param  ?string  $amazonSellerID  The Amazon seller ID of the seller for whom the shipment is being created. Required for SFP child account shipments.
     */
    public function __construct(
        public string $orderId,
        public ?string $amazonSellerID = null,
    ) {}
}
